import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowRight, Download, FileText } from "lucide-react";
import { PageHero, SectionHeading, SidebarNav } from "@/components/ui";
import { countries, organs } from "@/data/site";
import { createPageMetadata } from "@/lib/metadata";

export const metadata = createPageMetadata({ title: "About CCTTFA", description: "Learn about CCTTFA's history, mandate, governance organs, seven partner states and Permanent Secretariat.", path: "/about", image: "/images/about-hero.png" });

export default function AboutPage() {
  const navigation = [
    { label: "Our History", href: "#our-history" }, { label: "The Mandate", href: "#our-history" }, { label: "Governance Organs", href: "#governance-organs" }, { label: "Partner States", href: "#partner-states" }, { label: "Secretariat Leadership", href: "#secretariat-leadership" }, { label: "Strategic Protocols", href: "#strategic-protocols" },
  ];
  return <><PageHero eyebrow="Who we are" title="About CCTTFA" description="Connecting Seven Sovereign Nations to Global Maritime Pathways" image="/images/about-hero.png" position="center 38%" />
    <section className="section"><div className="site-container sidebar-layout"><SidebarNav items={navigation} /><div className="content-stack">
      <section id="our-history"><SectionHeading title="History & Mandate" description="The Central Corridor Transit Transport Facilitation Agreement (CCTTFA) was established on 2nd September 2006. Initially signed by five founding states, it is built on a shared mission to eliminate non-tariff trade barriers, upgrade critical rail, road, and port networks, and establish an uninterrupted flow of commodities." /><div className="timeline-cards"><article className="timeline-card"><strong>2006</strong><h3>The Founding Treaty</h3><p>Signed by five states to secure Dar es Salaam Port transit pathways.</p></article><article className="timeline-card"><strong>2010</strong><h3>Permanent Secretariat</h3><p>Operationalized in Dar es Salaam, coordinating meetings and facilitation.</p></article><article className="timeline-card"><strong>2023</strong><h3>Historic Accession</h3><p>Malawi acceded and Zambia entered the final accession process.</p></article></div></section>
      <section id="governance-organs"><SectionHeading title="Institutional Structure" description="CCTTFA&apos;s four organs work as one framework: strategic direction flows from the Council through oversight, consultation and implementation." /><div className="institutional-flow">{organs.map((organ, index) => <div key={organ.slug} className="institutional-flow-step"><Link href={`/about/organs/${organ.slug}`}><span>{index + 1}</span><div><h3>{organ.title}</h3><p>{organ.text}</p><small>View members & mandate <ArrowRight aria-hidden size={14} /></small></div></Link>{index < organs.length - 1 && <ArrowDown className="institutional-flow-arrow" aria-hidden size={24} />}</div>)}</div></section>
      <section id="partner-states"><SectionHeading title="Partner States" description="Open a Member State profile to explore routes, infrastructure, projects, trade information and national focal institutions." /><div className="country-card-grid">{countries.map((country) => <Link className="country-card" href={`/countries/${country.slug}`} key={country.slug}><h3><span><Image src={country.flag} alt="" fill sizes="2rem" /></span>{country.name}</h3><p>{country.description}</p><small>View country profile <ArrowRight aria-hidden size={14} /></small></Link>)}</div></section>
      <section id="secretariat-leadership"><SectionHeading title="Secretariat Leadership" description="The Permanent Secretariat translates governing-organ decisions into coordinated regional programmes and partnerships." /><article className="executive-context"><div><Image src="/images/leader-flory.png" alt="Adv. Okandju Okonge Flory, Executive Secretary" fill sizes="20rem" /></div><div><p className="eyebrow">Office of the Executive Secretary</p><h2>Adv. OKANDJU OKONGE Flory</h2><strong>Executive Secretary</strong><p>Leads treaty execution, institutional coordination, international partnerships and the day-to-day work of the CCTTFA Permanent Secretariat.</p><Link className="text-link" href="/about/executive-secretary">Read the Executive Secretary&apos;s Message <ArrowRight aria-hidden size={16} /></Link></div></article><div className="leadership-grid">{["Director — Name pending", "Director — Name pending"].map((title) => <article className="leader-card" key={title}><div><Image src="/images/avatar-placeholder.svg" alt="" fill sizes="20rem" /></div><h3>Awaiting Client Input</h3><strong>{title}</strong><p>Position to be confirmed by CCTTFA. Contact details not yet cleared for publication.</p></article>)}</div></section>
      <section id="strategic-protocols"><SectionHeading title="Strategic Documents" /><div className="document-list">{["CCTTFA Agreement (Amended December 2023)", "CCTTFA Protocols", "Awaiting client input — additional documents TBC"].map((title) => <article key={title}><FileText aria-hidden size={18} /><span>{title}</span><button type="button"><Download aria-hidden size={15} /> Download</button></article>)}</div></section>
    </div></div></section></>;
}
